### ISSUE TITLE
Реализовать ресурсы журнала проекта

### ISSUE THREAD

**Issue by kpojier** [AMTECH-dev/projectflow#25]
В рамках данной задачи необходимо:

- Реализовать запись в журнал изменений проекта;
- REST API журнала
Функционал должен быть покрыт тестами.

Project Journal
===============================================================

### List
`GET /projects/<projectId>/projectJournals?login=<string>&updateDate=<instant>`

Response
```json
{
    "data": [
        {
            "id": <bigint>,
            "updateDate": <instant>,
            "login": <string>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```
___________________________________________________________________

### Get by id
`GET /projects/<projectId>/projectJournals/<id>`

Response
```json
{
    "updateDate": <instant>,
    "login": <string>
}
```

**Comment by bratsever** [comment]
Добавить зависимость
```
<dependency>
    <groupId>com.vladmihalcea</groupId>
    <artifactId>hibernate-types-52</artifactId>
    <version>${hibernate-types.version}</version>
</dependency>
```

Расширить диалект для Postresql
```java
public class CustomPostgreSQLDialect extends PostgreSQL10Dialect {
    public CustomPostgreSQLDialect() {
        this.registerHibernateType(1111, JsonNodeBinaryType.class.getName());
        this.registerHibernateType(1111, JsonNodeStringType.class.getName());
    }
}
```
В конфиграция spring-boot указать конфигурацию
```
spring:
  jpa:
    database: postgresql
    database-platform: your.package..CustomPostgreSQLDialect
```

В entity для объекта указать
```
  @Type(type = "jsonb")
    @Column(name = "user_input", columnDefinition = "jsonb")
    private IClaimUserInput userInput;
```

Пример: https://vladmihalcea.com/java-map-json-jpa-hibernate/

**Comment by VladislavBakshanskij** [comment]
а где можно найти список кодов значений, которые регистрируются в конструкторе??
