### ISSUE TITLE
описать структуру БД и заполнить данными

### ISSUE THREAD

**Issue by VladislavBakshanskij** [AMTECH-dev/projectflow#3]
описать согласно нашим бумажкам.
описываем в визуальном представлении и связываем.

заполняем оргструктуру.

**Comment by Vartalex** [comment]
[projectflow_tables.txt](https://github.com/AMTECH-dev/projectflow/files/6507837/projectflow_tables.txt)


начальная версия бд.

- здесь не реализована проверка email'ов
- неясно, назначить delete restrict или cascade
- notification не проработана

**Comment by VladislavBakshanskij** [comment]
- нужно добавить проверку на номер телефона
- а как понять что письмо было отправлено? (может доп поле или запишем число попыток отправок?)
- нужно добавить defaultные значения к некоторым полям.

**Comment by KiraLis39** [comment]
* проверку на номер и т.п., как я пони маю, через регексы и CHECK (как и емейлы)? Можно и триггеры прикрутить, за одно;

* в письма - да, и количество попыток, и сообщение об ошибке, если возможно и т.п. как и у нас на доске нарисовано;
Я предлагал даже, при привышении порога неудачных попыток, отправлять уведомление поддержке;

* касательно delete - было предложение "сделать доступным удаления лишь для роли 'Администратор базы'", чтобы даже мы случайно не смогли вынести. Хотя нам оптимальнее учиться аккуратности и внимательности, как и архивации-восстановлению баз.

**Comment by kpojier** [comment]
```
--                     |<---------------------------------------------------------------------|
-- UNAPPROVED ---> ON_PL_PLANNING ---> ON_DL_APPROVING ---> ON_DIRECTOR_APPROVING --> DIRECTOR APPROVED --> DONE
--                     |<---------------------|<-----------------------|
```
