### ISSUE TITLE
Разработать спецификацию REST API сервиса

### ISSUE THREAD

**Issue by kpojier** [AMTECH-dev/projectflow#6]

**Comment by kpojier** [comment]
CRUD

GET  --- Read (v)
POST --- Create (x)
PUT -- Update (v)
DELETE -- Delete (v)

Auth
===========================================
### Login

`POST /login`

Request:
```
{
    "login": <string>,
    "password": <string>
}
```

Response:
```
{
    "accessToken": <stirng>,
    "refreshToken": <string>,
    "accessTokenExpiresAt": <timestamp>,
    "refreshTokenExpiresAt": <timestamp>,
}
```
### Exchange refresh token

`POST /refreshToken`

Request:
```
{
    "refreshToken": <string>
}
```

Response:
```
{
    "accessToken": <stirng>,
    "refreshToken": <string>,
    "accessTokenExpiresAt": <timestamp>,
    "refreshTokenExpiresAt": <timestamp>,
}
```

Users 
====================================

### Create

`POST /users`

```
{
    "employeeId" <bigint>,
    "password": <string>,
    "login": <string>
}
```

### List 

`GET /users?limit=<int>&offset=<int>&login=<string>&isLocked=<boolean>&orders=[-]<fieldName>`

```
{
    "data": [
        {
            "id": <bigint>,
            "login": <string>,
            "isLocked": <boolean>
        }    
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```

### Get by id

`GET /users/<id>`

```
{
    "login": <string>,
    "isLocked": <boolean>
}
```

### Update

`PUT /users/<id>`

```
{
    "login": <string>,
    "isLocked": <boolean>
}
```

### Delete

`DELETE /users/<id>`

### Password changing

`POST /users/<id>/password`

```
{
    "password": <string>
}
```

**Comment by kpojier** [comment]
Project Comment
===========================================

### Create
`POST /projects/<projectId>/comments`

```
{
    "message": <string>
}
```

### List
`GET /projects/<projectId>/comments?author=<string>&message=<string>&createDateFrom= <instant>&createDateTo= <instant>&limit=<int>&offset=<int>&orders=[-]<fieldName>`

Response
```
{
    "data": [
        {
            "id": <bigint>,
            "author": <string>,
            "message": <string>,
            "createDate": <instant>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```

### Update by id

`PUT /projects/<projectId>/comments/<commentId>`

Request
```
{
    "message": <string>
}
```

### Delete

`DELETE /projects/<projectId>/comments/<commentId>`

**Comment by kpojier** [comment]
Employee
===========================================
### Create
`POST /employees`

```
{
  
    "name": <string> // 1-255
    "email": <string>, // max 50, email-format
    "phone": <string>, // max 50, nullable
    "position": <enum: PROJECT_LEAD, DIRECTION_LEAD, DIRECTOR>, // not null
}
```

### List
`GET /employees?limit=<int>&offset=<int>&orders=[-]<fieldName>`

Response
```
{
    "data": [
        {
            "id": <bigint>,
            "name": <string>,
            "email": <string>,
            "phone": <string>,
            "position": <enum: PROJECT_LEAD, DIRECTION_LEAD, DIRECTOR>,
            "isFired": <bool>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```

### Get by id

`GET /employees/<id>`

Request
```
{
    "name": <string>,
    "email": <string>,
    "phone": <string>,
    "position": <enum: PROJECT_LEAD, DIRECTION_LEAD, DIRECTOR>,
    "isFired": <bool>
}
```

### Update by id

`PUT /employees/<id>`

Request
```
{
    "name": <string>,
    "email": <string>,
    "phone": <string>,
    "position": <enum: PROJECT_LEAD, DIRECTION_LEAD, DIRECTOR>,
    "isFired": <bool>
}
```

### Delete

`DELETE /employees/<id>`

Direction
===========================================

Project
===========================================

Project Flow
===========================================

Project Journal
===========================================

Milestone
===========================================

Notification
===========================================

Project Comments
===========================================

**Comment by KiraLis39** [comment]
Project

Create
POST /projects

{
    "name": <string> // 1-255
    "project_lead_id" <bigint>,
    "direction_id" <bigint>,
    "description" <string> // 1-2048,
    "create_date" <timestamptz> // not null,
    "status project_status" <?> //not null,
}

List
GET /projects?limit=<int>&offset=<int>&orders=[-]<fieldName>

Get by id
GET /projects/<id>

Update by id
PUT /projects/<id>

**Comment by Vartalex** [comment]
Project
========================================

### Create
`POST /projects`

Request:
```json
{
	"name": <string> 
	"projectLeadId": <bigint> 
	"directionId": <bigint> 
	"description": <string>
}
```

Response:
```json
{
	"id": <bigint>
	"name": <string> 
	"projectLeadId": <bigint>
	"directionId": <bigint> 
	"description": <string> 
	"createDate": <instant> 
	"status": <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>
}
```
_________________________________________________________________

### List
`GET /projects?limit=<int>&offset=<int>&name=<string>&projectLeadId=<bigint>&directionId=<bigint>&createDateStart=<instant>&createDateEnd=<instant>&status=<enum UNAPPROVED, ON_PL_PLANNING, ON_DL_APPROVING, ON_DIRECTOR_APPROVING, DIRECTOR_APPROVED, DONE>&orders=[-]<fieldname>`

Response:
```json
{
    "data": [
        {
            "id": <bigint>,
            "name": <string>,
            "projectLeadId": <bigint> 
            "projectLeadName": <string>
            "directionName": <string>
            "createDate": <instant>
            "status": <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}

```
_________________________________________________________________

### Get by id
`GET /projects/<id>`

Response:
```json
{
	"name": <string>,
	"projectLeadId": <bigint> ,
	"directionId": <bigint>,
	"description": <string>,
	"createDate": <instant>,
	"status": <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>,
        "milestones": [
                  {
                                 "id": <bigint>,
                                 "name": <string>,
                                 "description": <string>,
                                 "plannedStartDate": <instant>,
                                 "plannedFinishDate": <instant>,
                                 "factStartDate": <instant>,
                                 "factFinishDate": <instant>,
                                 "progressPercent": <short>
                  }
        ]
}
```
_________________________________________________________________

### Update by id
`PUT /projects/<id>`

Request:
```json
{
	"name": <string>,
	"projectLeadId": <bigint>
	"directionId": <bigint>
	"description": <string>
}
```
_________________________________________________________________

### Delete
`DELETE /projects/<id>`

**Comment by VladislavBakshanskij** [comment]
`+ -> not null`
`- -> null`


Project
=====================================
### **Create**
`POST /projects`

Request
```json
{
    "name": <string>, + // 1 - 255
    "projectLeadId": <bigint>, + 
    "directionId": <bigint>,  +
    "description": <string>, - // 0 - 2048
    "createDate": <timestamptz> -
}
```

Response
```json
{
    "id": <bigint>,
    "name": <string>, 
    "projectLeadId": <bigint>, 
    "directionId": <bigint>, 
    "description": <string>,
    "createDate": <timestamptz>
            "status": : <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>
}
```
_____________________________________
### **List**
`GET /projects?limit=<int>&offset=<int>&name=<string>&projectLeadId=<bigint>&directionId=<bigint>&createDate=<timestamp>&status=<enum UNAPPROVED, ON_PL_PLANNING,ON_DL_APPROVING, ON_DIRECTOR_APPROVING, DIRECTOR_APPROVED, DONE>&orders=[-]<fieldname>`

Reponse 
```json
{
    "data": [
        {
            "id": <bigint>,
            "name": <string>, 
            "projectLeadId": <bigint>, 
            "directionId": <bigint>, 
            "description": <string>,
            "createDate": <timestamp>,
            "status": : <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>
        }
    ], 
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```
_____________________________________
### **Get by id**
`GET /projects/<id>`

Response
```json
{
    "id": <bigint>,
    "name": <string>, 
    "projectLeadId": <bigint>, 
    "directionId": <bigint>, 
    "description": <string>,
    "createDate": <timestamp>,
    "status": : <enum: 'UNAPPROVED', 'ON_PL_PLANNING', 'ON_DL_APPROVING', 'ON_DIRECTOR_APPROVING', 'DIRECTOR APPROVED', 'DONE'>
}
```
__________________________________
### **Update by id**
`PUT /projects/<id>`

Request
```json
{
    "name": <string>,
    "projectLeadId": <bigint>, 
    "description": <string>
}
```

**Comment by VladislavBakshanskij** [comment]
Direction
=================================

### Create
`POST /directions`

Request
```json
{
    "name": <string>,
    "leadId": <bigint>
}
```

Response
```json
{
    "id": <bigint>,
    "leadId": <bigint>,
    "name": <string>,
    "leadName": <string>
}
```
_________________________________________

### List
`GET /directions?orders=[-]fieldname&limit=<int>&offset=<int>&name=<string>&leadId=<bigint>&leadName=<string>`

Response
```json
{
    "data": [
        {
            "id": <bigint>,
            "leadId": <bigint>,
            "name": <string>,
            "leadName": <string>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```
__________________________________________

### Get by id
`GET /directions/<id>`

Response
```json
{
    "leadId": <bigint>,
    "name": <string>,
    "leadName": <string>
}
```
__________________________________________

### Update by id
`PUT /directions/<id>`

Request
```json
{
    "name": <string>,
    "leadId": <bigint>
}
```
_________________________________________________________________

### Delete by id
`DELETE /directions/<id>`

**Comment by VladislavBakshanskij** [comment]
Milestone
========================================================

### Create
`POST /projects/<projectId>/milectones`

Request
```json
{
    "name": <string>,
    "description":  <string>,
    "plannedStartDate": <instant>,
    "plannedFinishDate": <instant>,
    "factStartDate": <instant>,
    "factFinishDate": <instant>,
    "progressPercent": <short>
}
```

Response
```json
{
    "id": <bigint>,
    "name": <string>,
    "description": <string>,
    "plannedStartDate": <instant>,
    "plannedFinishDate": <instant>,
    "factStartDate": <instant>,
    "factFinishDate": <instant>,
    "progressPercent": <short>
}
```
______________________________________________________________

### List
`GET /project/<projectId>/milestones/name=<string>&plannedStartDate=<instant>&plannedFinishDate=<instant>&factStartDate=<instant>&factFinishDate=<instant>&progressPercent=<short>&limit=<int>&offset=<int>&orders=[-]fieldname`

Response
```json
{
    "data": [
        {
            "id": <bigint>,
            "name": <string>,
            "plannedStartDate": <instant>,
            "plannedFinishDate": <instant>,
            "factStartDate": <instant>,
            "factFinishDate": <instant>,
            "progressPercent": <short>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```
_________________________________________________________________

### Get by id
`GET /projects/<projectId>/milestones/<id>`

Response
```json
{
    "name": <string>,
    "description": <string>,
    "plannedStartDate": <instant>,
    "plannedFinishDate": <instant>,
    "factStartDate": <instant>,
    "factFinishDate": <instant>,
    "progressPercent": <short>
}
```
_________________________________________________________________

### Update by id
`PUT /projects/<projectId>/milestones/<id>`

Request
```json
{
    "name": <string>,
    "description": <string>,
    "plannedStartDate": <instant>,
    "plannedFinishDate": <instant>,
    "factStartDate": <instant>,
    "factFinishDate": <instant>,
    "progressPercent": <short>
}
```
_________________________________________________________________

### Update percent by id
`PATCH /projects/<projectId>/milestones/<id>`

Request
```json
{
    "progressPercent": <short>
}
```

### Delete by id
`DELETE /projects/<projectId>/milestones/<id>`

**Comment by VladislavBakshanskij** [comment]
Project Journal
===============================================================

### List
`GET /projects/<projectId>/projectJournals?login=<string>&updateDate=<instant>`

Response
```json
{
    "data": [
        {
            "id": <bigint>,
            "updateDate": <instant>,
            "login": <string>
        }
    ],
    "meta": {
        "limit": <int>,
        "offset": <int>
    }
}
```
___________________________________________________________________

### Get by id
`GET /projects/<projectId>/projectJournals/<id>`

Response
```json
{
    "updateDate": <instant>,
    "login": <string>
}
```
